= `Name`
:toclevels: 4


+++The Name class provides the means to define any number of human readable  names for an object. A name is <b>not</b> to be used for defining inter-object relationships. For inter-object relationships instead use the object identification 'mRID'.+++


[cols="h,3",width=65%]
|===
| Type
| Class

| URI^xref:ROOT::uri_explanation.adoc[?]^
| `cim:Name`


| CIM standard (perspective)
| IEC61970 (Grid)



|===

== Class hierarchy
* *`Name`*


== Slots



.Associated classes
[d2,svg,theme=4]
----
vars: {
  d2-config: {
    pad: 20
  }
}
Name {
  style {
    fill: "#eccfcb"
    shadow: true
  }
}



NameType {
  style {
    fill: "#eccfcb"
    shadow: true
  }
}



IdentifiedObject {
  style {
    fill: "#eccfcb"
    shadow: true
  }
}




Name -> NameType: name_type


Name -> IdentifiedObject: identified_object


legend: "" {
  style: {
    fill: transparent
    stroke: transparent
  }
  grid-rows: 3
  grid-columns: 2
  grid-gap: 10
  near: bottom-right
  iec61968_color: "" {
    style: {
      fill: "#d1e7c2"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  iec61968_text: "IEC61968 (Enterprise)" {
    shape: text
  }
  iec61970_color: "" {
    style: {
      fill: "#eccfcb"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  iec61970_text: "IEC61970 (Grid)" {
    shape: text
  }
  iec62325_color: "" {
    style: {
      fill: "#fffbef"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  iec62325_text: "IEC62325 (Market)" {
    shape: text
  }
}
----


[cols="3,1,3,6",width=100%]
|===
| Name | Cardinalityxref:ROOT::cardinalities_explained.adoc[^?^,title="Explains stuff"] | Type | Description

| <<identified_object,`identified_object`>>
| 1
| xref::class/IdentifiedObject.adoc[`IdentifiedObject`]
| +++Identified object that this name designates.+++

| <<name_type,`name_type`>>
| 1
| xref::class/NameType.adoc[`NameType`]
| +++Type of this name.+++
|===

'''


//[discrete]
[#identified_object]
=== `identified_object`
+++Identified object that this name designates.+++

[cols="h,4",width=65%]
|===
| URI
| `cim:Name.IdentifiedObject`
| Cardinalityxref:ROOT::cardinalities_explained.adoc[^?^,title="Explains stuff"]
| 1
| Type
| xref::class/IdentifiedObject.adoc[`IdentifiedObject`]


|===

//[discrete]
[#name_type]
=== `name_type`
+++Type of this name.+++

[cols="h,4",width=65%]
|===
| URI
| `cim:Name.NameType`
| Cardinalityxref:ROOT::cardinalities_explained.adoc[^?^,title="Explains stuff"]
| 1
| Type
| xref::class/NameType.adoc[`NameType`]


|===


